services:
  crossword-solver-db:
    image: postgres:18-alpine
    container_name: crossword-solver-db
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crossword-solver-db